name: isro_quiz
description: Flutter project for ISRO quiz.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  flutter_native_splash: ^2.1.0
  modal_progress_hud: ^0.1.3
  lottie: ^1.2.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/
